name: Release CI

on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Generate build number
        id: buildnumber
        uses: einaregilsson/build-number@v1
        with:
          token: ${{secrets.github_token}}

      - name: Install GPG2
        run: sudo apt install gnupg2
      - name: Write private key
        run: echo -n ${{ secrets.GPG_PRIVATE }} | base64 -d >> private.gpg

      - name: Import private key
        run: gpg2 --allow-secret-key-import --import private.gpg

      - name: Test with Gradle
        run: ./gradlew test

      - name: Build with Gradle
        run: ./gradlew build

      - name: Release Build
        if: startsWith(github.ref, 'refs/tags/v')
        run: ./gradlew uploadArchives
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}