name: Staging CI

on:
  schedule:
    - cron: "0 0 * * 0"
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Write private key
      run: echo -n ${{ secrets.GPG_PRIVATE }} | base64 -d >> private.gpg
    - name: Import private key
      run: gpg --allow-secret-key-import --import private.gpg
    - name: Test with Gradle
      run: ./gradlew test
    - name: Build with Gradle
      run: ./gradlew build
